var rule = {
    title:'茶杯狐',
    编码:'',
    host:'https://www.cbportal.org',
    homeUrl:'/',
    url:'/fyclass/fypage.html[/fyclass/]',
    detailUrl:'https://www.cbportal.org/cupfox-dianying/fyid.html',
    searchUrl:'/cupfoxsearch/-------------/?wd=',
    searchable:1,
    quickSearch:0,
    filterable:0,
    filter:{},
    filter_url:'style={{fl.style}}&zone={{fl.zone}}&year={{fl.year}}&fee={{fl.fee}}&order={{fl.order}}',
    headers:{
        'User-Agent':'MOBILE_UA',
        "Cookie": "searchneed=ok"
    },
    timeout:5000,
    class_name:'电影&电视剧&动漫&综艺',
    class_url:'1&2&3&4',
    class_parse:'#side-menu:lt(1) li;a&&Text;a&&href;com/(.*?)/',
    cate_exclude:'',
    tab_exclude:'',
    play_parse:true,
    lazy:'',
    limit:6,
    double:true,
    推荐:'.col-sm-6;h3&&Text;img&&data-src;.date&&Text;a&&href',
    一级:'.col-sm-6;h3&&Text;img&&data-src;.date&&Text;a&&href',
    二级:'*',
    搜索:'.col-sm-6;h3&&Text;img&&data-src;.date&&Text;a&&href',
}
